Fix rpmbuild error found with v3.4.4 release
Local rpmbuild failed with v3.4.4 release with error:

error: Installed (but unpackaged) file(s) found:
   /usr/share/accel-config/contrib/configs/app_profile.conf
   /usr/share/accel-config/contrib/configs/net_profile.conf
   /usr/share/accel-config/contrib/configs/os_profile.conf
   /usr/share/accel-config/contrib/configs/profilenote.txt
   /usr/share/accel-config/contrib/configs/storage_profile.conf

These files are added as sample configs, and are supposed to be
installed to locations above. The installation of these files are
currently missing in SPEC file. This patch fixes it.

Signed-off-by: Yunying Sun <yunying.sun@intel.com>
Reviewed-by: Ramesh Thomas <ramesh.thomas@intel.com>